server:
  address: 0.0.0.0
  port: 8080
  error:
    include-stacktrace: never
spring:
  application:
    name: subscription
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mvc:
    throw-exception-if-no-handler-found: false
  web:
    resources:
      add-mappings: false
