server:
  address: 0.0.0.0
  port: 8080
  error:
    include-stacktrace: never
  tomcat:
    accesslog:
      enabled: true
    basedir: .

spring:
  application:
    name: subscription
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB__HOST}:${DB__PORT}/${DB__NAME}
    username: ${DB__USERNAME}
    password: ${DB__PASSWORD}
  session:
    jdbc:
      initialize-schema: always
    store-type: jdbc
  sql:
    init:
      mode: always
  mvc:
    throw-exception-if-no-handler-found: false
  web:
    resources:
      add-mappings: false
