server:
  address: 0.0.0.0
  port: 8080
  error:
    include-stacktrace: never
  tomcat:
    accesslog:
      enabled: true
    basedir: .

spring:
  application:
    name: subscription
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB__HOST}:${DB__PORT}/${DB__NAME}
    username: ${DB__USERNAME}
    password: ${DB__PASSWORD}
  kafka:
    producer:
      properties:
        spring.json.add.type.headers: false
    consumer:
      properties:
        spring.json.trusted.packages: "com.jjungs.subscription.domain.*"
  session:
    jdbc:
      initialize-schema: always
    store-type: jdbc
  sql:
    init:
      mode: always
  mvc:
    throw-exception-if-no-handler-found: false
  web:
    resources:
      add-mappings: false

kafka:
  bootstrap-servers: ${KAFKA__BOOTSTRAP_SERVERS}
  consumer:
    group-id: subscription-service
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    acks: all
    retries: 3
    enable-idempotence: true
